[package]
name = "floatmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "3.7.0"

[[bin]]
name = "floatmap"
path = "floatmap.rs"
