[package]
name = "rayondemo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"

[[bin]]
name = "rayondemo"
path = "rayondemo.rs"
